### ISSUE TITLE
Set endpoints for a venue in a configuration

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-cs-infra#17]

**Comment by galenatjpl** [comment]
@rtapella I don't think we had a chance to fully design this out yet.  We (U-CS) are planning on populating several SSM parameters that have to do with venue configuration, as part of the 23.2 release.  If this ticket is simply about populating this info, then perhaps this ticket can remain in 23.2 (since we are planning on populating much of this for 23.2).  Otherwise, if it's more complicated than that, I think we should push this to 23.3, and discuss more.

**Comment by galenatjpl** [comment]
@rtapella I'm going to go ahead and set this to 23.3 for now, but please let me know if you think we need to discuss more.

**Comment by rtapella** [comment]
I think it's okay to put into 23.3

**Comment by rtapella** [comment]
see https://github.com/unity-sds/unity-sds-portal/issues/3

**Comment by rtapella** [comment]
@galenatjpl how is this looking? Do you think we'd have something to test with by early Sept?

**Comment by galenatjpl** [comment]
@rtapella Are you okay if we close this ticket, since I think it's covered in 
https://github.com/unity-sds/unity-cs/issues/382
?
